name: jax
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.3.0=py310hecd8cb5_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h90acd4f_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=1.0=mkl
  - bleach=5.0.1=pyhd8ed1ab_0
  - bottleneck=1.3.5=py310h4e76f89_0
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2022.4.26=hecd8cb5_0
  - cffi=1.15.1=py310ha78151a_3
  - chex=0.1.5=py310hecd8cb5_0
  - comm=0.1.2=pyhd8ed1ab_0
  - debugpy=1.6.5=py310h7a76584_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dm-tree=0.1.7=py310hcec6c5f_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fftw=3.3.9=h9ed2024_1
  - flit-core=3.8.0=pyhd8ed1ab_0
  - icu=70.1=h96cf925_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - ipykernel=6.9.1=py310hecd8cb5_0
  - ipython=8.8.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jax=0.3.25=py310hecd8cb5_0
  - jaxlib=0.3.25=py310h5c6ac89_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.1=py310hecd8cb5_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_0
  - jupyter_contrib_nbextensions=0.7.0=pyhd8ed1ab_0
  - jupyter_core=5.1.3=py310h2ec42d9_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_highlight_selected_word=0.2.0=py310h2ec42d9_1005
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.6.1=pyhd8ed1ab_0
  - jupyter_server=2.1.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - libcxx=14.0.6=hccf4f1f_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libiconv=1.17=hac89ed1_0
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.40.0=ha978bb4_0
  - libxml2=2.10.3=hb9e07b5_0
  - libxslt=1.1.37=h5d22bc9_0
  - libzlib=1.2.13=hfd90126_4
  - llvm-openmp=14.0.6=h0dcd299_0
  - lxml=4.9.2=py310h0b20c97_0
  - markupsafe=2.1.1=py310h90acd4f_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py310hca72f7f_0
  - mkl_fft=1.3.1=py310hf879493_0
  - mkl_random=1.2.2=py310hc081a56_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.7=pyhd8ed1ab_0
  - nbconvert-core=7.2.7=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.7=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numexpr=2.8.4=py310h9638375_0
  - numpy=1.23.5=py310h9638375_0
  - numpy-base=1.23.5=py310ha98c3c9_0
  - openssl=3.0.9=hca72f7f_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optax=0.1.4=py310hecd8cb5_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.2=py310h3ea8b11_0
  - pandoc=2.19.2=h694c41f_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=22.3.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.4=py310h90acd4f_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h90acd4f_0
  - python=3.10.8=he7542f4_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-json-logger=2.0.4=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2022.7=py310hecd8cb5_0
  - pyyaml=6.0=py310h90acd4f_5
  - pyzmq=25.0.0=py310hf615a82_0
  - readline=8.1.2=h3899abd_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - scikit-learn=1.2.0=py310hcec6c5f_1
  - scipy=1.9.3=py310h09290a1_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.6.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - toolz=0.12.0=py310hecd8cb5_0
  - tornado=6.2=py310h90acd4f_1
  - tqdm=4.64.1=py310hecd8cb5_0
  - traitlets=5.8.1=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - pip:
      - astropy==5.2.1
      - contourpy==1.0.7
      - corner==2.2.2
      - cycler==0.11.0
      - fonttools==4.38.0
      - ipympl==0.9.3
      - jaxopt==0.6
      - kiwisolver==1.4.4
      - matplotlib==3.6.3
      - pillow==9.4.0
      - pyerfa==2.0.0.1
      - pyparsing==3.0.9
      - scienceplots==2.0.1
      - seaborn==0.12.2
      - sklearn==0.0.post1
      - tinygp==0.2.3
prefix: /opt/anaconda3/envs/jax
